<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="CloseCommand" Id="{1e939fe3-1a80-44e6-a98e-1b39eeabb5e8}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'no_explicit_call' := 'LightOnCommand is a CLASS and must be accessed using methods or properties'}
FUNCTION_BLOCK CloseCommand IMPLEMENTS I_Command
VAR
	_closeCommand					: I_CloseCommand;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
// The body of a class must not be used for code.  
// Cyclic code should be called from a method if needed. 
]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{7bdb00be-3f3f-4429-9b01-3335264a77fe}">
      <Declaration><![CDATA[METHOD Execute
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_closeCommand.Close();]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{60a130d8-8440-48df-9b90-447a30f7ffb1}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	CloseCommand			: I_CloseCommand;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_closeCommand  := CloseCommand;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>